# Generated by Django 4.2.13 on 2024-06-27 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("django", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="officer",
            options={
                "ordering": ["name"],
                "verbose_name": "Officer",
                "verbose_name_plural": "Officers",
            },
        ),
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["name"],
                "verbose_name": "Person",
                "verbose_name_plural": "Persons",
            },
        ),
        migrations.AlterModelOptions(
            name="vehicle",
            options={
                "ordering": ["license_plate"],
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
            },
        ),
        migrations.CreateModel(
            name="Infraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("comments", models.TextField()),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="infractions",
                        to="django.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Infraction",
                "verbose_name_plural": "Infractions",
                "ordering": ["vehicle"],
            },
        ),
    ]
